FROM ubuntu:latest
RUN apt-get update && apt-get install -y python3
# VULN: secret en ENV
ENV DATABASE_PASSWORD=supersecret123
ENV AWS_SECRET_KEY=AKIAIOSFODNN7EXAMPLE
# VULN: pas de USER (tourne en root)
COPY . /app
CMD ["python3", "/app/exchange.py"]
